WebSiteForAPI/ContactManagerWebSite/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ContactManagerWebSite.Models
{
    public class ContactModel
    {
        
        [DisplayName("Contact Name")]
        public string Name { get; set; }
        
        [DisplayName("Contact Phone Number")]
        public string PhoneNumber { get; set; }
        public string Note { get; set; }
    }
}

WebSiteForAPI/ContactManagerWebSite/Controllers/ContactManagerController.cs
using ContactManagerWebSite.Models;
using ContactManagerWebSite.Processor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting;
using System.Web;
using System.Web.Mvc;
using WebService.Models;

namespace ContactManagerWebSite.Controllers
{
    public class ContactManagerController : Controller
    {
        public async System.Threading.Tasks.Task<ActionResult> SaveContact()
        {

            var contact = new Contact
            {
                Name = "Name from WebSite UI 1",
                PhoneNumber = "00001111",
                Note = "Note from WebSite UI 1"
            };

            if (contact == null) ViewBag.Message = "Model was not Bound";
            else
            {

                var success = await ContactManagerProcessor.ProcessContact(contact);

                if (success == true)
                    ViewBag.Message = "Contact Saved Successfully!";
                else
                    ViewBag.Message = "Contact Save Failed!";
            }

            return View();
        }


        /* ==================================================================================================
         * NOTE:    for post actions, always create two view methods
         *          one for the actual View to get object information with form
         *          next for the HTTP Post Action for posting form values to API/Db
         */

        public ActionResult CreateContact()
        {
            return View(new ContactModel());
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> CreateContact(ContactModel contact)
        {
            var saveResult = await CreateAndSaveContact(contact);

            if (saveResult == true)
                ViewBag.Message = $"{contact.Name}: Contact Saved Successfully!";
            else
                ViewBag.Message = $"{contact.Name}: Contact Save Failed!";

            return View("SaveContact");
        }
        // ==================================================================================================

        private async System.Threading.Tasks.Task<bool> CreateAndSaveContact(ContactModel contactModel)
        {
            var contact = new Contact
            {
                Name = contactModel.Name,
                PhoneNumber = contactModel.PhoneNumber,
                Note = contactModel.Note
            };

            return await ContactManagerProcessor.ProcessContact(contact);
        }


        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return View();
        //}

        public ActionResult ViewContact()
        {
            ViewBag.Message = "Contacts ";

            List<Contact> contacts = ContactManagerProcessor.GetAllContacts();

            return View(contacts);
        }
    }
}

WebSiteForAPI/ContactManagerWebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContactManagerWebSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebSiteForAPI/ContactManagerWebSite/Views/ContactManager/CreateContact.cshtml
@model ContactManagerWebSite.Models.ContactModel

@{
    ViewBag.Title = "CreateContact";
}

<h2>CreateContact</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ContactModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

WebSiteForAPI/ContactManagerWebSite/Views/ContactManager/SaveContact.cshtml
<h2>Save Contact</h2>
<br />
<h3>@ViewBag.Message</h3>

WebSiteForAPI/ContactManagerWebSite/Views/ContactManager/ViewContact.cshtml
@model IEnumerable<WebService.Models.Contact>

@{
    ViewBag.Title = "ViewContact";
}

<h2>ViewContact</h2>

<p>
    @Html.ActionLink("Create Contact", "CreateContact", "ContactManager")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

WebSiteForAPI/ContactManagerWebSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebSiteForAPI/ContactManagerWebSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebSiteForAPI/ContactManagerWebSite/Views/Home/Index.cshtml
@*@{
    ViewBag.Title = "Home Page";
}*@

    <div class="jumbotron">
        <h1>Save Contact to Web API database</h1>

        <br />
        <br />

        <p>@Html.ActionLink("Save Contact", "SaveContact", "ContactManager") </p>

        <br />

        <p>@Html.ActionLink("Create and Save Contact", "CreateContact", "ContactManager") </p>

        <br />

        <p>@Html.ActionLink("Contacts", "ViewContact", "ContactManager") </p>

    </div>

@*<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

WebSiteForAPI/ContactManagerWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacts", "ViewContact", "ContactManager")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>